controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

    # Pour mettre la page Home par défaut
home:
    path: /
    controller: App\Controller\HomeController::index

